[project]
name = "job-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
    "motor>=3.3.0",
    "pytest>=8.2.0",
    "pytest-asyncio>=0.23.5",
]
