# This is the pre-commit config for the project.
# It is used to run the pre-commit hooks on the project.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^services/job-api/.*\.py$
      - id: ruff-format
        files: ^services/job-api/.*\.py$

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^services/job-api/.*\.py$

  - repo: local
    hooks:
      - id: e2e test-suite
        name: Run E2E Test Suite
        entry: tests/run_e2e_tests.sh
        language: script
        pass_filenames: false
        verbose: true
        always_run: true
      - id: job-api-unit-tests
        name: Run job-api unit tests
        entry: sh -c 'export PATH="$HOME/.local/bin:$PATH" && cd services/job-api && uv run pytest -q'
        language: system
        pass_filenames: false
        files: ^services/job-api/
