version: "3.9"

services:
  job-api:
    build:
      context: ./services/job-api
      dockerfile: Dockerfile
    working_dir: /app
    command: uv run uvicorn main:app --reload --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
