# This is the docker-compose file for the development environment.
# It is used to run the application in a development environment.
# It is run by the Makefile.

version: "3.9"
name: model-infer-app

networks:
  model-infer-app-net:
    external: true
    name: model-infer-app-net

services:
  job-api:
    build:
      context: ./services/job-api
      dockerfile: Dockerfile
    working_dir: /app
    command: uv run uvicorn main:app --reload --host 0.0.0.0 --port 8080
    environment:
      - REPO_BACKEND=${REPO_BACKEND:-mongo}
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017}
    networks:
      - model-infer-app-net
    ports:
      - "8080:8080"
  distilbert:
    build:
      context: ./services/models
      dockerfile: distilbert/Dockerfile
    working_dir: /app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8091
    environment:
      - MODEL_ID=${MODEL_ID:-distilbert-base-uncased-finetuned-sst-2-english}
      - TORCH_DEVICE=${TORCH_DEVICE:-cpu}
      - MAX_INPUT_TOKENS=${MAX_INPUT_TOKENS:-512}
      - REQUEST_TIMEOUT_SECONDS=${REQUEST_TIMEOUT_SECONDS:-10}
    networks:
      - model-infer-app-net
    ports:
      - "8091:8091"
  vqa:
    build:
      context: ./services/models
      dockerfile: vqa/Dockerfile
    working_dir: /app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8092
    environment:
      - MODEL_ID=${MODEL_ID:-dandelin/vilt-b32-finetuned-vqa}
      - TORCH_DEVICE=${TORCH_DEVICE:-cpu}
      - MAX_INPUT_TOKENS=${MAX_INPUT_TOKENS:-512}
      - REQUEST_TIMEOUT_SECONDS=${REQUEST_TIMEOUT_SECONDS:-10}
    networks:
      - model-infer-app-net
    ports:
      - "8092:8092"
  yolo:
    build:
      context: ./services/models
      dockerfile: yolo/Dockerfile
    working_dir: /app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8093
    networks:
      - model-infer-app-net
    ports:
      - "8093:8093"
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: LV8JJ6IQSB6PCzb7bIMZig
    networks:
      - model-infer-app-net
